- name: theblower
  hosts: dbservers
  become: yes
  tasks:
  - name: install Python3
    apt:
      name: python3
      state: present
  
  - name: install pip3
    apt:
      name: python3-pip
      state: present

  - name: install mastodon.py
    pip:
      name: mastodon.py
      state: present
  
  - name: install couchdb
    snap:
      name: couchdb
      state: present
  
  - name: install couchdb python library
    pip:
      name: couchdb
      state: present

  - name: install requests
    pip:
      name: requests
      state: present

  - name: run mastodon api theblower python script
    command: python3 TestRESTMastodon.py
  


  